name: delivery_user
description: deliver application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  font_awesome_flutter: ^10.4.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
#  flutter_map: ^3.1.0
#  geocoder: ^0.2.1
#  tuple: any
#  positioned_tap_detector_2: any,
  flutter_osm_plugin: ^0.53.4
  screenshot: ^1.3.0

  transparent_image: any
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.6.0
  zoom_tap_animation: ^1.1.0
  location: ^4.4.0
  image_picker: ^0.8.7+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
#
#<<<<<<< HEAD
#
#  flutter_lints: ^2.0.0
#=======
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
#>>>>>>> ca47965444b9ac964d5cdfbc1ae5475f88e7a0c0


flutter:


  uses-material-design: true


  assets:
    - assets/svg/


  
  fonts:
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
    - family: Poppins-BlackItalic
      fonts:
        - asset: assets\fonts\Poppins-BlackItalic.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets\fonts\Poppins-Bold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets\fonts\Poppins-ExtraBold.ttf
    - family: Poppins-BolrdItalic
      fonts:
        - asset: assets\fonts\Poppins-BoldItalic.ttf
    - family: Poppins-ExtraBoldItalic
      fonts:
        - asset: assets\fonts\Poppins-ExtraBoldItalic.ttf
    - family: Poppins-ExtraLight
      fonts:
        - asset: assets\fonts\Poppins-ExtraLight.ttf
    
    - family: Poppins-ExtraLightItalic
      fonts:
        - asset: assets\fonts\Poppins-ExtraLightItalic.ttf
    - family: Poppins-Italic
      fonts:
        - asset: assets\fonts\Poppins-Italic.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets\fonts\Poppins-Light.ttf
    - family: Poppins-LightItalic
      fonts:
        - asset: assets\fonts\Poppins-LightItalic.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets\fonts\Poppins-Medium.ttf
    - family: Poppins-MediumItalic
      fonts:
        - asset: assets\fonts\Poppins-MediumItalic.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets\fonts\Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets\fonts\Poppins-SemiBold.ttf
    - family: Poppins-SemiBoldItalic
      fonts:
        - asset: assets\fonts\Poppins-SemiBoldItalic.ttf
    - family: Poppins-Thin
      fonts:
        - asset: assets\fonts\Poppins-Thin.ttf
    - family: Poppins-ThinItalic
      fonts:
        - asset: assets\fonts\Poppins-ThinItalic.ttf
  
 
